name: artifact-build

'on': workflow_dispatch

jobs:
  build-artifact:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Code checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU for arm64
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/arm64
      -
        name: Build Prusa Slicer for ubuntu 22.04/arm64
        env:
          LATEST_VERSION: "version_2.3.1"
          DPKG_ARCH: "amd64"
          APPIMAGE_ARCH: "aarch64"
          ARCH: "aarch64"
        run: |
          docker run --env LATEST_VERSION --env DPKG_ARCH --env APPIMAGE_ARCH --env ARCH --platform linux/amd64 -v "$(pwd)":/app --workdir=/app ubuntu:focal ./build.sh
      -
        name: Upload Prusa Slicer artifact version 2.3.1 for ubuntu 22.04/arm64
        run: dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n
